server:
  port: 8090
llama:
  base-url: http://127.0.0.1:8080
jwt:
  tokenHeader: Authorization
  secret: WvqWxVY0NuX469fNVMVT3YsJmLevE6Vk4TOwfwqhVOaiGYLE8jTtmmclg7Zm/LOAbRJKPq5SAzlWh0NI7Y01urMPvreS13eo89hb7YaDd7k=
  expiration: 604800
  tokenHead: 'Bearer '
spring:
  application:
    name: llama-backend
  profiles:
    active: dev
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
mybatis:
  mapper-locations:
    - classpath:com/workspace/llmsystem/mapper/*.xml
    - classpath:dao/*.xml
secure:
  ignored:
    urls:
      - /swagger-ui/
      - /swagger-resources/**
      - /**/v2/api-docs
      - /**/*.html
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.map
      - /favicon.ico
      - /actuator/**
      - /druid/**
      - /user/login
      - /user/register
      - /user/info
      - /user/logout
      - /minio/upload
redis:
  database: aichat
  key:
    user: 'ums:user'
  expire:
    common: 86400
spring:
  datasource:
    url: jdbc:mysql://root:WuZLxcHAUXygNDTEndKDIwtMvhXDCBEd@nozomi.proxy.rlwy.net:19106/aichat
    username: root
    password: WuZLxcHAUXygNDTEndKDIwtMvhXDCBEd
    druid:
      initial-size: 5
      min-idle: 10
      max-active: 20
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
      stat-view-servlet:
        login-username: druid
        login-password: druid
  data:
    redis:
      host: localhost
      database: 0
      port: 6379
      password:
      timeout: 300ms
logging:
  level:
    root: info
    com.workspace.llmsystem: debug
logstash:
  host: localhost
  enableInnerLog: false
llama:
  base-url: http://127.0.0.1:8080
