spring:
  datasource:
    url: jdbc:mysql://localhost:3306/aichat?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Ho_Chi_Minh&useSSL=false
    username: root
    password: 1234
    druid:
      initial-size: 5
      min-idle: 10
      max-active: 20
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet:
        login-username: druid
        login-password: druid
  data:
    redis:
      host: localhost
      database: 0
      port: 6379
      password:
      timeout: 300ms
logging:
  level:
    root: info
    com.workspace.llmsystem: debug
logstash:
  host: localhost
  enableInnerLog: false