spring:
  datasource:
    url: jdbc:mysql://${MYSQLHOST}:${MYSQLPORT}/${MYSQLDATABASE}
    username: ${MYSQLUSER}
    password: ${MYSQLPASSWORD}
    druid:
      initial-size: 5
      min-idle: 10  
      max-active: 20
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
      stat-view-servlet:
        login-username: druid
        login-password: druid
  data:
    redis:
      host: ${REDISHOST}
      database: 0
      port: ${REDISPORT}
      password: ${REDISPASSWORD}
      timeout: 300ms
logging:
  level:
    root: info
    com.workspace.llmsystem: debug
logstash:
  host: localhost
  enableInnerLog: false
llama:
  base-url: http://127.0.0.1:8080